# Generated by Django 3.1.3 on 2020-11-27 22:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=16, unique=True)),
                ('payment_name', models.CharField(max_length=26)),
                ('name_on_card', models.CharField(max_length=30)),
                ('cvv_number', models.CharField(max_length=3)),
                ('billing_street', models.CharField(max_length=35)),
                ('billing_city', models.CharField(max_length=35)),
                ('billing_state', models.CharField(max_length=35)),
                ('billing_postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('item_list', models.CharField(max_length=500)),
                ('total_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('street', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('postal_code', models.CharField(max_length=5)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name_on_card', models.CharField(max_length=30)),
                ('credit_card_number', models.CharField(max_length=16, unique=True)),
                ('cvv_number', models.CharField(max_length=3)),
                ('billing_street', models.CharField(max_length=35)),
                ('billing_city', models.CharField(max_length=35)),
                ('billing_state', models.CharField(max_length=35)),
                ('billing_postal_code', models.CharField(max_length=5)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('order_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Request to Cancel', 'Request to Cancel'), ('Nothing to Order', 'Nothing to Order')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=320)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('staff_id', models.IntegerField()),
                ('item_list', models.CharField(max_length=500)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('order_status', models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Deleted', 'Deleted')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('street', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('postal_code', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=35)),
            ],
        ),
    ]
