# Generated by Django 3.1.3 on 2020-11-28 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_request_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Request to Cancel', 'Request to Cancel'), ('Nothing to Order', 'Nothing to Order')], default='Nothing to Order', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cvv_number',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')]),
        ),
    ]
